apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-v0
spec:
  selector:
    matchLabels:
      app: app-v0
  replicas: 1 
  template:
    metadata:
      labels:
        app: app-v0
    spec:
      containers:
      - name: app-v0
        image: ratulb/rocket-app-v0:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: service-v0
spec:
  selector:
    app: app-v0
  type: ClusterIP
  ports:
  - name: service-port
    protocol: TCP
    port: 8080
    targetPort: 8080

---
#istio does not support k8s default ingress backend - following does the job of default ingress backend with istio
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: default-backend-v0
spec:
  #ingressClassName: istio
  rules:
  - http:
      paths:
      - path: /.*
        pathType: ImplementationSpecific #Prefix does not work
        backend:
          service:
            name: service-v0
            port:
              number: 8080

